version: '3'
services:
  app:
    image: firmansyahprofess/realworld-api-quarkus-native-cicd:latest
    environment:
      DB_URL: jdbc:db2://db:9092/testdb:user=sa;password=xWmGrW0hi4;
      DB_USER: sa
      DB_PASSWORD: xWmGrW0hi4
    ports:
      - "8080:8080"
    networks:
      - factor-nt
    depends_on:
      db:
        condition: service_healthy
        

  db:
    image: icr.io/db2_community/db2 # https://www.ibm.com/docs/en/db2/11.5?topic=deployments-db2-community-edition-docker
    container_name: db2-database
    platform: linux/x86_64
    privileged: true
    ports:
      - "9092:9092"  # Map host port to Db2 container's port
    environment:
      - LICENSE=accept
      - DB2INSTANCE=db2inst1
      - DB2INST1_PASSWORD=xWmGrW0hi4
      - DBNAME=testdb
      - IS_OSXFS=true
      - BLU=false
      - ENABLE_ORACLE_COMPATIBILITY=false
      - HEALTH_CHECK_TIMEOUT=30  # Adjust as needed
    volumes:
      - db2-data:/database  # Persist Db2 data
    healthcheck:
      test: ["CMD", "db2", "connect", "to", "testdb", "sa", "db2inst1", "using", "xWmGrW0hi4"]
      # test: ["CMD-SHELL", "su - db2inst1 -c \"db2gcf -s\""]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s  # Give Db2 some time to initialize
    
    
  postman-node:
    build:
      context: ../../../.
      dockerfile: src/main/docker/Dockerfile.native.cicd.postman.node
    volumes:
      - ../../../src/main/postman:/app/postman
      - ../../../target/postman:/app/target/postman
    #command: ["sh", "-c", "./postman/run.api.tests.sh && ./k6/run.api.tests.sh"] 
    networks:
      - factor-nt
    environment:
      APIURL: http://app:8080/api
    depends_on:
      - app
      
  k6-node:
    build:
      context: ../../../.
      dockerfile: src/main/docker/Dockerfile.native.cicd.k6.node
    volumes:
      - ../../../src/main/k6:/app/k6
      - ../../../target/k6:/app/target/k6
    #command: ["/app/k6/run.api.tests.sh"]
    networks:
      - factor-nt
    environment:
      APIURL: http://app:8080/api
    depends_on:
      - app
      
networks:
  factor-nt:
    name: factor-nt
    driver: bridge

volumes:
  db2-data:
