# created by the factor : Feb 23, 2024, 6:45:22 AM  
# Use the official k6 image from Grafana as the base image
FROM grafana/k6:latest

# Set the working directory
WORKDIR /app

# Set the entrypoint to run the script (optional)
ENTRYPOINT ["/bin/sh","./k6/factor.run.tests.on.local.sh"]