// created by the factor : Dec 9, 2023, 8:25:21 AM  
version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-network

networks:
  jenkins-network:

volumes:
  jenkins-data: