# created by the factor : May 30, 2024, 6:48:44 AM  
# Use the official Postman Newman image as the base
FROM postman/newman:alpine

# install html and htmlextra
RUN npm uninstall -g newman newman-reporter-htmlextra newman-reporter-html
RUN npm install -g newman newman-reporter-htmlextra newman-reporter-html

# Set the working directory
WORKDIR /app

# Set the entrypoint to run the script (optional)
ENTRYPOINT ["/bin/sh","./postman/factor.run.tests.on.local.sh"]