# created by the factor : Dec 7, 2023, 4:03:00 PM  
# Use the official k6 image from Grafana as the base image
FROM grafana/k6:latest

# Set the working directory
WORKDIR /app

# Set the entrypoint to run the script (optional)
ENTRYPOINT ["/bin/sh","./k6/factor.run.tests.on.local.sh"]