# created by the factor : Dec 9, 2023, 9:19:14 AM  
# Use the official k6 image from Grafana as the base image
FROM grafana/k6:latest

# Set the working directory
WORKDIR /app

# Set the entrypoint to run the script (optional)
ENTRYPOINT ["/bin/sh","./k6/factor.run.tests.on.local.sh"]