# created by the factor : Dec 9, 2023, 11:59:29 AM  
name: Factor CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
         

      - name: Grant execute permissions
        run: |
          chmod +x ./src/main/docker/factor/integrated.cicd.native.sh
          chmod +x ./mvnw
          mkdir -p ./target/k6/reports
          sudo chmod -R +rw ./target/k6/reports/
          mkdir -p ./target/postman/reports
          sudo chmod -R +rw ./target/postman/reports/
          mkdir -p ./target/zap
          sudo chmod -R +rw ./target/zap/
          touch ./target/postman/factor.postman_complete
          touch ./target/k6/factor.k6_complete
          touch ./target/zap/factor.zap_complete
          
      - name: Run Script
        run: |
          export DOCKER_PASSWORD=$DOCKER_PASSWORD
          export DOCKER_USER=$DOCKER_USER
          ./src/main/docker/factor/integrated.cicd.native.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}

